_target_: src.models.cloth_segmenter.unet_clothes_segment
# define cfg of each of the arguments
arch :  'unet'
encoder_name : "resnet34"
encoder_weights : "imagenet"
in_channels : 3
classes : 1


optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 1e-4
  weight_decay: 0.0
#partial means we are not defining all args
scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  _partial_: true



  step_size : 1
  gamma : 0.1
  verbose: True

